import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/navbar";
import { FavoritesProvider } from "@/components/context/FavoriteContext";
import { SearchHistoryProvider } from "@/components/context/SearchHistoryContext";

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <SearchHistoryProvider>
          <FavoritesProvider>
            <Header />
            {children}
          </FavoritesProvider>
        </SearchHistoryProvider>
      </body>
    </html>
  );
}
